/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Y4l6ADDFCmg
 */
import Link from "next/link"
import { Popover } from "@/components/ui/popover"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"

export function crearInvitacion() {
  return (
    <div className="grid md:grid-cols-[300px_1fr] items-start max-w-5xl w-full gap-0 md:gap-0 rounded-none border">
      <div className="hidden md:flex flex-col border-r border-true-gray-200">
        <div className="flex-1 p-4 space-y-4">
          <Link className="flex items-center space-x-2" href="#">
            <HomeIcon className="h-6 w-6" />
            <span className="font-semibold">Home</span>
          </Link>
          <Link className="flex items-center space-x-2" href="#">
            <FileEditIcon className="h-6 w-6" />
            <span className="font-semibold">Edit</span>
          </Link>
          <Link className="flex items-center space-x-2" href="#">
            <UsersIcon className="h-6 w-6" />
            <span className="font-semibold">Users</span>
          </Link>
          <Link className="flex items-center space-x-2" href="#">
            <SettingsIcon className="h-6 w-6" />
            <span className="font-semibold">Settings</span>
          </Link>
        </div>
      </div>
      <div className="flex flex-col min-h-screen">
        <div className="flex items-center p-4 border-b md:hidden">
            <Popover>
            <div className="flex items-center space-x-2">
              <MoreHorizontalIcon className="h-5 w-5" />
            </div>
            <div>
              <div className="grid gap-1">
                <Link className="flex items-center space-x-2 p-2" href="#">
                  <HomeIcon className="h-4 w-4" />
                  <span>Home</span>
                </Link>
                <Link className="flex items-center space-x-2 p-2" href="#">
                  <FileEditIcon className="h-4 w-4" />
                  <span>Edit</span>
                </Link>
                <Link className="flex items-center space-x-2 p-2" href="#">
                  <UsersIcon className="h-4 w-4" />
                  <span>Users</span>
                </Link>
                <Link className="flex items-center space-x-2 p-2" href="#">
                  <SettingsIcon className="h-4 w-4" />
                  <span>Settings</span>
                </Link>
              </div>
            </div>
          </Popover>
        </div>
        <div className="flex-1 p-4 space-y-4">
          <div className="space-y-4">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold">Form</h1>
              <p className="text-gray-500 dark:text-gray-400">Record information about an invitation to a meeting.</p>
            </div>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label className="text-sm" htmlFor="purpose">
                  Purpose
                </Label>
                <Input id="purpose" required />
              </div>
              <div className="space-y-2">
                <Label className="text-sm" htmlFor="people">
                  People in charge
                </Label>
                <Select className="min-h-[32px]" id="people" multiple placeholder="Select people">
                  <option>One</option>
                  <option>Two</option>
                  <option>Three</option>
                  <option>Four</option>
                  <option>Five</option>
                </Select>
              </div>
              <div className="space-y-2">
                <Label className="text-sm" htmlFor="content">
                  Content
                </Label>
                <div className="grid gap-2">
                  <Textarea className="min-h-[100px]" id="content" placeholder="Enter your message" />
                  <Textarea className="min-h-[100px]" id="content2" placeholder="Enter your message" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function FileEditIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 13.5V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-5.5" />
      <polyline points="14 2 14 8 20 8" />
      <path d="M10.42 12.61a2.1 2.1 0 1 1 2.97 2.97L7.95 21 4 22l.99-3.95 5.43-5.44Z" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function MoreHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </svg>
  )
}
